"""Lote 7: triage masivo Steam — central + referencia menor."""
from generate_db import game, v

STEAM_BATCH7_GAMES = [
    game(
        "the-almamula",
        "The Almamula",
        None,
        "publicado",
        v("principal", "principal", None),
        "Gaucho Forge",
        "Argentina",
        ["PC"],
        ["aventura", "supervivencia"],
        "Survival cooperativo en el litoral argentino: los gauchos deben cazar al Almamula mientras una maldición azota la región.",
        {
            "regiones": ["Noreste", "Pampeana"],
            "provincias": ["Chaco", "Corrientes"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["folclore", "gauchesco", "terror"],
        },
        {
            "steam": "https://store.steampowered.com/app/3219760/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3219760/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3219760/4b159349bf64d20a77530bf587897ffa775b8982/header.jpg?t=1775955394",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "avaroth-online",
        "Avaroth Online",
        None,
        "publicado",
        v("principal", "principal", None),
        "IWG Studio / Luis Merino SR",
        "Argentina",
        ["PC"],
        ["mmorpg", "rpg"],
        "MMORPG de mundo abierto con PvP y progresión en tierras inspiradas en Argentina.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["cultura_popular"],
        },
        {
            "steam": "https://store.steampowered.com/app/2784670/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2784670/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2784670/c9ff8a13eccbf20c40056c07e3fb51e61ad24e5b/header.jpg?t=1780190512",
            "capturas": [],
        },
        metadatos={"idiomas": ["es"], "multijugador": True, "precio": None, "rating": {}, "tipo": "juego"},
        ejes_culturales=["historia"],
        tipo_obra="indie",
    ),
    game(
        "ethereal",
        "ETHEREAL",
        None,
        "publicado",
        v("principal", None, None),
        "Nicolás Recabarren / Tomás Batista",
        "Argentina",
        ["PC"],
        ["puzzle", "aventura"],
        "Puzles atmosféricos en un mundo misterioso, desarrollado por el dúo argentino Recabarren y Batista.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["arte", "indie"],
        },
        {
            "steam": "https://store.steampowered.com/app/751220/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/751220/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/751220/header.jpg?t=1556113441",
            "capturas": [],
        },
        tipo_obra="indie",
    ),
    game(
        "the-path-into-the-abyss",
        "The Path Into The Abyss",
        None,
        "publicado",
        v("principal", "principal", None),
        "MXR Productions",
        "Argentina",
        ["PC"],
        ["accion", "supervivencia"],
        "Shooter de supervivencia en primera persona ambientado en Buenos Aires con horror cósmico y combate hardcore.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["Ciudad Autónoma de Buenos Aires"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["terror", "cultura_urbana"],
        },
        {
            "steam": "https://store.steampowered.com/app/3000460/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3000460/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3000460/header.jpg?t=1765825788",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "game-of-patios",
        "Game Of Patios",
        None,
        "publicado",
        v("principal", "principal", None),
        "Córdoba Digital Lab",
        "Argentina",
        ["PC"],
        ["aventura", "simulacion"],
        "Teo vuelve a su barrio cordobés para ayudar a su abuela en el concurso de patios: regar, decorar y resolver enigmas.",
        {
            "regiones": ["Centro"],
            "provincias": ["Córdoba"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["cultura_urbana", "folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/3387790/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3387790/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3387790/b02f0fa23fc5b6b5227949e280dc63b4023b6ef0/header.jpg?t=1762171346",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "envido",
        "Envido",
        None,
        "publicado",
        v("principal", None, None),
        "Gaucho Forge",
        "Argentina",
        ["PC"],
        ["estrategia", "cartas"],
        "Juego de cartas argentino con almas en pena, pulpería y macumbas: bluff, estrategia y folklore gauchesco.",
        {
            "regiones": ["Pampeana"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["juegos_tradicionales", "gauchesco", "folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/3872160/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3872160/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3872160/24d93d462daf5f9320362a8bb6939e469b877fb0/header.jpg?t=1783016487",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "gaucho-and-the-grassland",
        "Gaucho and the Grassland",
        None,
        "publicado",
        v("principal", "principal", None),
        "Epopeia Games",
        "Brasil",
        ["PC"],
        ["aventura", "simulacion"],
        "Aventura acogedora como vaquero latinoamericano: explorar la pradera, ayudar a la comunidad y convivir con seres místicos.",
        {
            "regiones": ["Pampeana", "Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["gauchesco", "folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/1670830/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1670830/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1670830/9f21a0ecf942c1cffe4caaa81ec90716fb55c9df/header.jpg?t=1783110660",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
        grado_relevancia_argentina="central",
    ),
    game(
        "the-baron-got-you-again",
        "The baron got you again",
        None,
        "publicado",
        v("principal", "principal", None),
        "XXII GROUP",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "Escape room de acción: sos un agente secreto prisionero en una base del Barón Von Rimmel en el interior de Argentina.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["accion", "humor"],
        },
        {
            "steam": "https://store.steampowered.com/app/538050/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/538050/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/538050/header.jpg?t=1501761466",
            "capturas": [],
        },
        tipo_obra="indie",
    ),
    game(
        "help-no-brake",
        "HELP NO BRAKE",
        None,
        "publicado",
        v("principal", None, None),
        "Edgar Mendoza",
        "Argentina",
        ["PC"],
        ["plataformas", "accion"],
        "Plataformas frenéticas: manejá sin frenos y llegá al final de cada nivel sin explotar el auto.",
        {
            "regiones": ["Cuyo"],
            "provincias": ["Mendoza"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["arcade"],
        },
        {
            "steam": "https://store.steampowered.com/app/2531960/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2531960/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2531960/header.jpg?t=1718326546",
            "capturas": [],
        },
        tipo_obra="indie",
    ),
    game(
        "borealis-descent",
        "Borealis Descent",
        None,
        "publicado",
        v("principal", "principal", None),
        "Zabdiel Mendoza",
        "Argentina",
        ["PC"],
        ["accion", "terror"],
        "Shooter de extracción en tercera persona en un mundo postapocalíptico solarpunk con atmósfera contaminada.",
        {
            "regiones": ["Cuyo"],
            "provincias": ["Mendoza"],
            "periodo_historico": ["futurista"],
            "temas": ["terror", "ciencia_ficcion"],
        },
        {
            "steam": "https://store.steampowered.com/app/2161980/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2161980/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2161980/header.jpg?t=1686365703",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "youra-the-game",
        "Youra The Game",
        None,
        "publicado",
        v("principal", "principal", None),
        "Julio Carmona / Jose Mendoza / Derek Krull",
        "Argentina",
        ["PC"],
        ["aventura", "rpg"],
        "RPG de acción sobre destino, poderes elementales y la lucha entre luz y oscuridad.",
        {
            "regiones": ["Cuyo"],
            "provincias": ["Mendoza"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["fantasia"],
        },
        {
            "steam": "https://store.steampowered.com/app/2724180/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2724180/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2724180/45110161de98020c8ec13b3f1cc53ff01eef00e2/header.jpg?t=1763587409",
            "capturas": [],
        },
        tipo_obra="indie",
    ),
    game(
        "rhythm-soccer",
        "Rhythm Soccer",
        None,
        "publicado",
        v("referencia_menor", None, "principal", "futbol"),
        "One More Play",
        "Argentina",
        ["PC"],
        ["deportes", "ritmo"],
        "Juego de ritmo con selecciones de Brasil, Argentina, Italia y Alemania: acertá la nota para pasar y disparar.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["deporte"],
        },
        {
            "steam": "https://store.steampowered.com/app/2368200/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2368200/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2368200/header.jpg?t=1705791859",
            "capturas": [],
        },
        deporte={"deporte": "futbol", "competicion": ["Copa internacional"], "equipos_destacados": ["Selección Argentina"], "modo": "ritmo"},
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "havana-blood",
        "Havana Blood",
        None,
        "publicado",
        v("referencia_menor", "principal", None),
        "BRYPER INDUSTRIES",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "Shooter noir de crimen ambientado en La Habana y Miami; el protagonista se llama Héctor Mendoza.",
        {
            "regiones": ["Cuyo"],
            "provincias": ["Mendoza"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["accion"],
        },
        {
            "steam": "https://store.steampowered.com/app/4361180/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4361180/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4361180/d330d1d1c690d50c5a5cf0b11c0247c5305c0759/header.jpg?t=1777310415",
            "capturas": [],
        },
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "pampas-selene-maze-of-demons",
        "Pampas & Selene: The Maze of Demons",
        None,
        "publicado",
        v("referencia_menor", None, None),
        "@unepic_fran",
        "España",
        ["PC"],
        ["plataformas", "aventura"],
        "Metroidvania estilo MSX2 del creador de Unepic; título evoca la pampa aunque el estudio es español.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["La Pampa"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["retro"],
        },
        {
            "steam": "https://store.steampowered.com/app/1966220/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1966220/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1966220/header.jpg?t=1733382932",
            "capturas": [],
        },
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "piggo",
        "PIGGO",
        None,
        "publicado",
        v("referencia_menor", None, None),
        "PampaWorks",
        "Argentina",
        ["PC"],
        ["party", "cartas"],
        "Party multijugador de cartas caótico: reuní cuatro iguales, engañá a tus amigos y reaccioná al instante.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["La Pampa"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["humor", "juegos_tradicionales"],
        },
        {
            "steam": "https://store.steampowered.com/app/4597790/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4597790/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/4597790/d42d9bdc425fe2974c51d0cfcb8ec93cd1ec88c6/header.jpg?t=1779660396",
            "capturas": [],
        },
        metadatos={"idiomas": ["es"], "multijugador": True, "precio": None, "rating": {}, "tipo": "juego"},
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "warpzone-vs-the-dimension",
        "WarpZone vs THE DIMENSION",
        None,
        "publicado",
        v("referencia_menor", None, None),
        "PampaFox",
        "Argentina",
        ["PC"],
        ["accion", "arcade"],
        "Beat'em up cooperativo con estética de los 90 y visión moderna.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["La Pampa"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["arcade"],
        },
        {
            "steam": "https://store.steampowered.com/app/1088060/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1088060/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1088060/header.jpg?t=1604685422",
            "capturas": [],
        },
        metadatos={"idiomas": ["en"], "multijugador": True, "precio": None, "rating": {}, "tipo": "juego"},
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "hive-dive",
        "Hive Dive",
        None,
        "publicado",
        v("referencia_menor", None, None),
        "PewPew Studio",
        "Argentina",
        ["PC"],
        ["accion", "arcade"],
        "Shooter on-rails infinito pilotando un dron por paisajes de la Patagonia argentina.",
        {
            "regiones": ["Patagonia"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["geografia"],
        },
        {
            "steam": "https://store.steampowered.com/app/2707380/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2707380/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2707380/header.jpg?t=1750195495",
            "capturas": [],
        },
        ejes_culturales=["geografia"],
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "curilemu",
        "Curilemu",
        None,
        "publicado",
        v("referencia_menor", "principal", None),
        "Austral Games / Abstract Digital",
        "Chile",
        ["PC"],
        ["aventura", "terror"],
        "Horror de aventura inspirado en mitos de la Patagonia chilena y horrores lovecraftianos.",
        {
            "regiones": ["Patagonia"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["folclore", "terror"],
        },
        {
            "steam": "https://store.steampowered.com/app/2362780/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2362780/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2362780/header.jpg?t=1729367624",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "arcana-ucsb",
        "Arcana",
        None,
        "publicado",
        v("referencia_menor", None, None),
        "UCSB Gaucho Game Lab",
        "Estados Unidos",
        ["PC"],
        ["accion", "rpg"],
        "Roguelike de magia y oleadas de enemigos; el estudio universitario usa el apodo Gaucho sin vínculo con Argentina.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["fantasia"],
        },
        {
            "steam": "https://store.steampowered.com/app/3037740/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3037740/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3037740/header.jpg?t=1741368645",
            "capturas": [],
        },
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "wanted-guns",
        "Wanted Guns",
        None,
        "publicado",
        v("referencia_menor", "principal", None),
        "Iridon Interactive / Nerlaska Studios",
        "España",
        ["PC"],
        ["accion", "aventura"],
        "Western donde el reverendo Devlin enfrenta el retorno de Los Gauchos, una banda mexicana de forajidos.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["siglo_xix"],
            "temas": ["gauchesco", "western"],
        },
        {
            "steam": "https://store.steampowered.com/app/2462230/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2462230/"],
        },
        imagenes={
            "portada": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2462230/header.jpg?t=1690483555",
            "capturas": [],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
]
