"""Lote 5: barrido Steam — juegos argentinos central/importante."""
from generate_db import game, v

STEAM_BATCH5_GAMES = [
    game(
        "malon",
        "Malón",
        None,
        "publicado",
        v("principal", "principal", None),
        "LTP Argentina",
        "Argentina",
        ["PC"],
        ["estrategia", "simulacion"],
        "Administrá un fortín fronterizo entre la Pampa y la Patagonia: construí, reclutá soldados y resistí ataques en un escenario de frontera argentina.",
        {
            "regiones": ["Pampeana", "Patagonia"],
            "provincias": ["La Pampa", "Santa Cruz", "Chubut"],
            "periodo_historico": ["siglo_xix"],
            "temas": ["historia", "gauchesco", "folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/3462960/Malon/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3462960/Malon/"],
        },
        ejes_culturales=["historia", "folclore"],
        tipo_obra="indie",
    ),
    game(
        "aesir-online",
        "AESIR Online",
        None,
        "publicado",
        v("principal", "principal", None),
        "Leandro Mendoza / Agustin Di Lauro",
        "Argentina",
        ["PC"],
        ["mmorpg", "rpg"],
        "MMORPG desarrollado en Godot por un equipo argentino, inspirado en Argentum Online de finales de los 90.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["cultura_popular"],
        },
        {
            "steam": "https://store.steampowered.com/app/2324940/AESIR_Online/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2324940/AESIR_Online/"],
        },
        metadatos={"idiomas": ["es"], "multijugador": True, "precio": "gratuito", "rating": {}, "tipo": "juego"},
        ejes_culturales=["historia"],
        tipo_obra="indie",
        disponibilidad="gratis",
    ),
    game(
        "qsvt-que-se-vayan-todos",
        "QSVT: ¡Que se vayan todos!",
        None,
        "publicado",
        v("principal", "principal", None),
        "Sendero tecnológico",
        "Argentina",
        ["PC"],
        ["estrategia", "simulacion"],
        "Estrategia política satírica donde conducís una fuerza política, competís en elecciones y tomás decisiones sobre el destino del país.",
        {
            "regiones": ["Nacional"],
            "provincias": ["Ciudad Autónoma de Buenos Aires"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["politica", "humor"],
        },
        {
            "steam": "https://store.steampowered.com/app/4187700/QSVT_Que_se_vayan_todos/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4187700/QSVT_Que_se_vayan_todos/"],
        },
        ejes_culturales=["politica", "satira"],
        tipo_obra="indie",
        sensibilidad="media",
    ),
    game(
        "chacal",
        "CHACAL",
        None,
        "publicado",
        v("principal", "principal", None),
        "Pernich Media",
        "Argentina",
        ["PC"],
        ["accion", "arcade"],
        "Bullet hell que recorre el sur y el centro del país hasta enfrentar al presidente Francisco en una cruzada arcade por liberar la nación.",
        {
            "regiones": ["Nacional", "Pampeana"],
            "provincias": ["Ciudad Autónoma de Buenos Aires"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["politica", "satira"],
        },
        {
            "steam": "https://store.steampowered.com/app/1528370/CHACAL/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1528370/CHACAL/"],
        },
        ejes_culturales=["politica", "satira"],
        tipo_obra="indie",
        sensibilidad="media",
    ),
    game(
        "funeraria-marquez-paz",
        "Servicio de Funeraria Marquez Paz",
        None,
        "publicado",
        v("principal", "principal", None),
        "devpetrichor",
        "Argentina",
        ["PC"],
        ["aventura", "accion"],
        "Aventura en las calles de Marquez Paz: laburás para la funeraria, explorás el barrio y te metés en situaciones violentas para ganar plata.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["Buenos Aires"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["cultura_urbana", "humor"],
        },
        {
            "steam": "https://store.steampowered.com/app/1885040/Funerary_Services_Marquez_Paz/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1885040/Funerary_Services_Marquez_Paz/"],
        },
        ejes_culturales=["cultura_urbana"],
        tipo_obra="indie",
    ),
    game(
        "dead-world",
        "Dead World",
        None,
        "publicado",
        v("principal", "principal", None),
        "Milanesa Studio",
        "Argentina",
        ["PC"],
        ["shooter", "accion"],
        "FPS en primera persona ambientado en una Argentina post-apocalíptica devastada por la guerra, siguiendo el viaje de Miguel de regreso a casa.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["ciencia_ficcion", "memoria"],
        },
        {
            "steam": "https://store.steampowered.com/app/1376960/Dead_World/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1376960/Dead_World/"],
        },
        ejes_culturales=["memoria"],
        tipo_obra="indie",
    ),
    game(
        "built-brick-by-brick",
        "Built Brick by Brick",
        None,
        "publicado",
        v("principal", None, None),
        "Monte Castro Studios",
        "Argentina",
        ["PC"],
        ["simulacion"],
        "Simulación de vida y construcción en el campo argentino: empezás con un terreno, laburás para financiar la casa soñada.",
        {
            "regiones": ["Pampeana"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["geografia", "cultura_popular"],
        },
        {
            "steam": "https://store.steampowered.com/app/3819930/Built_Brick_by_Brick/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3819930/Built_Brick_by_Brick/"],
        },
        ejes_culturales=["geografia"],
        tipo_obra="indie",
    ),
    game(
        "anothers-memories",
        "Another's Memories",
        None,
        "publicado",
        v("principal", None, None),
        "Altun Studios",
        "Argentina",
        ["PC"],
        ["terror", "aventura"],
        "Terror psicológico en primera persona ambientado en una casa de campo argentina, con puzzles y enemigos en un entorno opresivo.",
        {
            "regiones": ["Pampeana"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/3955730/Anothers_Memories/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3955730/Anothers_Memories/"],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "en-busca-de-la-libertad",
        "En busca de la libertad",
        None,
        "publicado",
        v("principal", "principal", None),
        "Pierucci Studios",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "En un Argentina invadida por zombies políticos, un héroe libertario y su equipo investigan el origen del virus Qu-K antes del colapso total.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["politica", "satira", "humor"],
        },
        {
            "steam": "https://store.steampowered.com/app/4119760/In_Search_of_Freedom/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4119760/In_Search_of_Freedom/"],
        },
        ejes_culturales=["politica", "satira"],
        tipo_obra="indie",
        sensibilidad="media",
    ),
    game(
        "drident",
        "Drident",
        None,
        "publicado",
        v("principal", None, None),
        "Big Mount Interactive",
        "Argentina",
        ["PC"],
        ["terror", "aventura"],
        "Survival horror corto en un bosque neblinoso de Argentina: investigás desapariciones, experimentos prohibidos y criaturas grotescas.",
        {
            "regiones": ["Patagonia", "Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/4806100/Drident/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4806100/Drident/"],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "gaucho-subway-escape",
        "Gaucho: Subway Escape",
        None,
        "publicado",
        v("principal", "principal", None),
        "SymbioStudio",
        "Argentina",
        ["PC"],
        ["accion", "roguelike"],
        "Buenos Aires cayó y el subte se volvió un infierno: combates de parry contra jefes demoníacos para escapar y salvar a tu gato Gaucho.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["Ciudad Autónoma de Buenos Aires"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["cultura_urbana", "ciencia_ficcion"],
        },
        {
            "steam": "https://store.steampowered.com/app/3272390/Gaucho_Subway_Escape/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3272390/Gaucho_Subway_Escape/"],
        },
        ejes_culturales=["cultura_urbana", "folclore"],
        tipo_obra="indie",
    ),
    game(
        "tierras-infernales",
        "Tierras Infernales",
        None,
        "publicado",
        v("principal", "principal", None),
        "Fichiner",
        "Argentina",
        ["PC"],
        ["accion", "roguelike"],
        "Roguelike arcade de acción ambientado en una distopía de las guerras de independencia en el norte argentino.",
        {
            "regiones": ["Noroeste"],
            "provincias": ["Salta", "Jujuy"],
            "periodo_historico": ["independencia", "siglo_xix"],
            "temas": ["independencia", "historia"],
        },
        {
            "steam": "https://store.steampowered.com/app/3297900/Infernal_Lands/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/3297900/Infernal_Lands/"],
        },
        ejes_culturales=["historia"],
        tipo_obra="indie",
    ),
    game(
        "el-tango-de-la-muerte",
        "El Tango de la Muerte",
        2018,
        "publicado",
        v("principal", "principal", None),
        "Hernán Smicht",
        "Argentina",
        ["PC"],
        ["arcade", "musica"],
        "Juego de ritmo y melodrama en la Argentina de 1923: Luciano debe aprender tango para conquistar a Martita antes de su cumpleaños.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["Ciudad Autónoma de Buenos Aires"],
            "periodo_historico": ["siglo_xx"],
            "temas": ["cultura_popular", "historia"],
        },
        {
            "steam": "https://store.steampowered.com/app/701380/El_Tango_de_la_Muerte/",
            "web_oficial": "http://www.eltangodelamuerte.com",
            "fuentes_investigacion": ["https://store.steampowered.com/app/701380/El_Tango_de_la_Muerte/"],
        },
        ejes_culturales=["musica", "historia"],
        tipo_obra="indie",
    ),
    game(
        "yerba-mate-tycoon",
        "Yerba Mate Tycoon",
        None,
        "publicado",
        v("principal", None, None),
        "DonislawDev",
        "Polonia",
        ["PC"],
        ["simulacion", "estrategia"],
        "Tycoon de gestión sobre la producción de yerba mate: creá marcas, probá aditivos y hacé crecer tu empresa en el negocio del mate.",
        {
            "regiones": ["Nacional", "Litoral"],
            "provincias": ["Misiones", "Corrientes"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["cultura_popular", "juegos_tradicionales"],
        },
        {
            "steam": "https://store.steampowered.com/app/1404560/Yerba_Mate_Tycoon/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1404560/Yerba_Mate_Tycoon/"],
        },
        ejes_culturales=["folclore", "juegos_tradicionales"],
        tipo_obra="comercial",
        grado_relevancia_argentina="importante",
        calidad_fuente="tienda",
    ),
    game(
        "defensores-del-barrio",
        "DEFENSORES DEL BARRIO",
        None,
        "publicado",
        v("principal", "principal", None),
        "Pernich Media",
        "Argentina",
        ["PC"],
        ["arcade", "accion"],
        "Arcade con tres minijuegos sobre héroes argentinos que defienden un comedor infantil, el ambiente y el espacio público.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["politica", "educacion"],
        },
        {
            "steam": "https://store.steampowered.com/app/4309130/DEFENSORES_DEL_BARRIO/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4309130/DEFENSORES_DEL_BARRIO/"],
        },
        ejes_culturales=["politica", "educativo"],
        tipo_obra="indie",
    ),
    game(
        "pista-motorsport",
        "PISTA Motorsport",
        None,
        "publicado",
        v("principal", None, None),
        "REG Simulations",
        "Argentina",
        ["PC"],
        ["deportes", "simulacion"],
        "Simulador de carreras con autos de competición argentinos y circuitos emblemáticos del automovilismo local.",
        {
            "regiones": ["Nacional", "Pampeana"],
            "provincias": ["Buenos Aires", "Córdoba"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["deporte"],
        },
        {
            "steam": "https://store.steampowered.com/app/2434120/PISTA_Motorsport/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2434120/PISTA_Motorsport/"],
        },
        ejes_culturales=["deporte"],
        tipo_obra="indie",
    ),
    game(
        "panchofobia",
        "Panchofobia",
        None,
        "publicado",
        v("principal", "principal", None),
        "Bajonero Noctambulo",
        "Argentina",
        ["PC"],
        ["terror", "aventura"],
        "De noche salís a comprar un pancho y terminás enredado en secretos inquietantes y una secta panzer en la Buenos Aires nocturna.",
        {
            "regiones": ["Pampeana"],
            "provincias": ["Ciudad Autónoma de Buenos Aires"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["cultura_urbana", "humor"],
        },
        {
            "steam": "https://store.steampowered.com/app/4568220/Panchofobia/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4568220/Panchofobia/"],
        },
        ejes_culturales=["cultura_urbana", "satira"],
        tipo_obra="indie",
    ),
    game(
        "take-a-hint",
        "Take a Hint",
        2026,
        "publicado",
        v("principal", "principal", None),
        "Floramisu / Byutaki",
        "Argentina",
        ["PC"],
        ["aventura", "educativo"],
        "Novela visual gratuita argentina: Delfina intenta convencer a su amiga Ailén de que su novio no es bueno para ella. Women Game Jam 2023.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["educacion", "cultura_popular"],
        },
        {
            "steam": "https://store.steampowered.com/app/4297760/Take_a_Hint/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4297760/Take_a_Hint/"],
        },
        metadatos={"idiomas": ["es"], "multijugador": False, "precio": "gratuito", "rating": {}, "tipo": "juego"},
        ejes_culturales=["educativo"],
        tipo_obra="indie",
        disponibilidad="gratis",
    ),
    game(
        "zonda",
        "Zonda",
        None,
        "publicado",
        v("principal", None, None),
        "Bennu Games",
        "Argentina",
        ["PC"],
        ["aventura", "narrativa"],
        "Thriller narrativo en los cerros de San Juan: el Autódromo El Zonda guarda un silencio con nombre propio.",
        {
            "regiones": ["Cuyo"],
            "provincias": ["San Juan"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["geografia", "historia"],
        },
        {
            "steam": "https://store.steampowered.com/app/4560800/Zonda/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/4560800/Zonda/"],
        },
        ejes_culturales=["geografia"],
        tipo_obra="indie",
    ),
    game(
        "tenebris-somnia",
        "Tenebris Somnia",
        None,
        "en_desarrollo",
        v("principal", "principal", None),
        "Andrés Borghi / Saibot Studios",
        "Argentina",
        ["PC"],
        ["terror", "aventura"],
        "Survival horror 2D con actores reales y acertijos, en desarrollo por el estudio argentino Saibot (Doorways).",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/2121510/Tenebris_Somnia/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2121510/Tenebris_Somnia/"],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
    game(
        "doorways-holy-mountains",
        "Doorways: Holy Mountains of Flesh",
        None,
        "publicado",
        v("principal", None, None),
        "Saibot Studios",
        "Argentina",
        ["PC"],
        ["terror", "aventura"],
        "Aventura de terror en primera persona del estudio argentino Saibot Studios, con atmósfera opresiva y acertijos.",
        {
            "regiones": ["Nacional"],
            "provincias": [],
            "periodo_historico": ["contemporaneo"],
            "temas": ["folclore"],
        },
        {
            "steam": "https://store.steampowered.com/app/383930/Doorways_Holy_Mountains_of_Flesh/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/383930/Doorways_Holy_Mountains_of_Flesh/"],
        },
        ejes_culturales=["folclore"],
        tipo_obra="indie",
    ),
]
