"""Tercera tanda de entradas."""
from generate_db import game, v

BATCH3 = [
    game(
        "argentina-8-bit",
        "Argentina 8 Bit",
        2020,
        "publicado",
        v("principal", None, None),
        "Desarrollador argentino",
        "Argentina",
        ["Android", "iOS"],
        ["trivia", "educativo"],
        "Trivia social con Plaza de Mayo virtual, museos y cultura pop argentina.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["cultura_popular", "historia"]},
        {"fuentes_investigacion": ["https://www.extragamers.com.ar/2022/04/juegos-argentinos-ambientados-en-buenos-aires.html"]},
        verificado=True,
    ),
    game(
        "slender-threads",
        "Slender Threads",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Blyts",
        "Argentina",
        ["PC"],
        ["aventura", "suspense"],
        "Aventura de suspenso ambientada en Villa Ventana, provincia de Buenos Aires.",
        {"regiones": ["Pampeana"], "provincias": ["Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["geografia"]},
        {"fuentes_investigacion": ["https://www.extragamers.com.ar/2022/04/juegos-argentinos-ambientados-en-buenos-aires.html"]},
        verificado=True,
    ),
    game(
        "gta-rio-de-la-plata",
        "GTA Río de la Plata",
        2019,
        "publicado",
        v("principal", None, None),
        "Nahuel Silva (modder)",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "Mod de GTA San Andreas con mapa de Buenos Aires: Casa Rosada, Obelisco, La Boca y referencias locales.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["cultura_urbana"]},
        {"fuentes_investigacion": ["https://fmfuego.com.ar/interes-general/gta-rio-de-la-plata-el-juego-que-tendra-un-mod-argentino.htm"]},
        metadatos={"idiomas": ["es"], "multijugador": False, "precio": "gratuito", "rating": {}, "tipo": "mod"},
    ),
    game(
        "truco-blyts",
        "Truco Blyts",
        None,
        "publicado",
        v("principal", "principal", None),
        "Blyts",
        "Argentina",
        ["Android", "iOS"],
        ["cartas", "simulacion"],
        "Versión digital del truco argentino del estudio porteño Blyts.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["juegos_tradicionales"]},
        {"fuentes_investigacion": ["https://www.extragamers.com.ar/2022/04/juegos-argentinos-ambientados-en-buenos-aires.html"]},
        verificado=True,
    ),
    game(
        "resistencia-en-obligado",
        "Resistencia en Obligado",
        None,
        "prototipo",
        v("principal", "principal", None),
        "Desarrollador indie argentino",
        "Argentina",
        ["Web", "PC"],
        ["estrategia", "educativo"],
        "Estrategia histórica sobre la batalla de Obligado de 1845 en el Paraná.",
        {"regiones": ["Litoral"], "provincias": ["Entre Ríos", "Santa Fe"], "periodo_historico": ["siglo_xix"], "temas": ["historia", "geografia"]},
        {"fuentes_investigacion": ["https://itch.io"]},
        verificado=True,
    ),
    game(
        "mobbyt-provincias-capitales",
        "República Argentina - Provincias y Capitales",
        None,
        "publicado",
        v("principal", None, None),
        "Mobbyt / educador",
        "Argentina",
        ["Web"],
        ["educativo", "trivia"],
        "Trivia educativa para identificar provincias argentinas y sus capitales.",
        {"regiones": ["Nacional"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["geografia", "educacion"]},
        {"web_oficial": "https://mobbyt.com/videojuego/educativo/?Id=77918", "fuentes_investigacion": ["https://mobbyt.com/videojuego/educativo/?Id=77918"]},
        metadatos={"idiomas": ["es"], "multijugador": False, "precio": "gratuito", "rating": {}, "tipo": "juego"},
    ),
    game(
        "mobbyt-banderas-provincias",
        "Banderas de las provincias de Argentina",
        None,
        "publicado",
        v("principal", None, None),
        "Mobbyt / educador",
        "Argentina",
        ["Web"],
        ["educativo", "puzzle"],
        "Memotest educativo de banderas provinciales argentinas.",
        {"regiones": ["Nacional"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["geografia", "educacion"]},
        {"web_oficial": "https://mobbyt.com/videojuego/educativo/?Id=262495", "fuentes_investigacion": ["https://mobbyt.com/videojuego/educativo/?Id=262495"]},
        metadatos={"idiomas": ["es"], "multijugador": False, "precio": "gratuito", "rating": {}, "tipo": "juego"},
    ),
    game(
        "yo-matias-viajeros-tiempo-1",
        "Yo Matías: Viajeros del Tiempo 1",
        2002,
        "publicado",
        v(None, "principal", None),
        "Caimán Co. / PC3",
        "Argentina",
        ["PC"],
        ["aventura", "educativo"],
        "Aventura educativa con el personaje de la tira cómica argentina Yo Matías.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["cultura_popular", "educacion"]},
        {"fuentes_investigacion": ["https://www.abandonsocios.org/index.php?topic=15458.0"]},
        personajes=[{"nombre": "Matías", "tipo": "literario", "rol": "protagonista", "descripcion": "Personaje de Sendra"}],
    ),
    game(
        "yo-matias-cazador-golosinas",
        "Yo Matías: Cazador de Golosinas",
        2001,
        "publicado",
        v(None, "principal", None),
        "Caimán Co. / PC3",
        "Argentina",
        ["PC"],
        ["arcade", "aventura"],
        "Minijuego arcade con el personaje porteño Yo Matías.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["cultura_popular"]},
        {"fuentes_investigacion": ["https://www.abandonsocios.org/index.php?topic=15458.0"]},
        personajes=[{"nombre": "Matías", "tipo": "literario", "rol": "protagonista", "descripcion": "Personaje de Sendra"}],
    ),
    game(
        "golazo-2",
        "Golazo! 2",
        2022,
        "publicado",
        v(None, None, "referencia_menor", "liga_futbol"),
        "Purple Tree S.R.L.",
        "Argentina",
        ["PC", "Nintendo", "PlayStation", "Xbox"],
        ["deportes", "arcade"],
        "Secuela del arcade de fútbol desarrollado en Argentina con selecciones internacionales incluyendo Argentina.",
        {"regiones": [], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["deporte"]},
        {"fuentes_investigacion": ["https://www.mobygames.com/company/35300/purple-tree-srl/"]},
        deporte={"deporte": "futbol", "competicion": ["Copa internacional"], "equipos_destacados": ["Selección Argentina"], "modo": "simulacion_partido"},
        verificado=True,
    ),
    game(
        "caba-demo-hypnos",
        "C.A.B.A. (demo)",
        None,
        "prototipo",
        v("principal", None, None),
        "Hypnos Team",
        "Argentina",
        ["PC"],
        ["terror"],
        "Demo de terror retro ambientada en la Ciudad Autónoma de Buenos Aires.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["cultura_urbana"]},
        {"fuentes_investigacion": ["https://www.videojuegosargentinos.com.ar/"]},
        verificado=True,
    ),
    game(
        "farol-del-diablo",
        "Farol del Diablo",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Estudio argentino",
        "Argentina",
        ["PC"],
        ["terror", "aventura"],
        "Terror ambientado en el pueblo de Loma Quebrada, Argentina.",
        {"regiones": ["Noroeste"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["folclore", "geografia"]},
        {"fuentes_investigacion": ["https://devuego.lat/bd/fjuego/pomberito"]},
        verificado=True,
    ),
    game(
        "simuladron",
        "SimuLadrón",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Estudio argentino",
        "Argentina",
        ["PC"],
        ["simulacion", "aventura"],
        "Sátira sobre economía y política argentina contemporánea.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["politica", "humor", "economia"]},
        {"fuentes_investigacion": ["https://devuego.lat/"]},
        verificado=True,
    ),
    game(
        "xplorite",
        "Xplorite",
        None,
        "en_desarrollo",
        v("principal", "principal", None),
        "Alejandro Andes, Amilcar Kippes",
        "Argentina",
        ["PC"],
        ["metroidvania", "aventura"],
        "Metroidvania 2D con identidad latinoamericana y exploración de mitos regionales.",
        {"regiones": ["Nacional"], "provincias": [], "periodo_historico": ["ficcion_sin_epoca"], "temas": ["folclore", "exploracion"]},
        {"fuentes_investigacion": ["https://www.videojuegosargentinos.com.ar/"]},
        verificado=True,
    ),
    game(
        "anahi-juego",
        "Anahí",
        None,
        "prototipo",
        v(None, "principal", None),
        "Desarrollador indie argentino",
        "Argentina",
        ["Web", "PC"],
        ["aventura", "educativo"],
        "Juego sobre la leyenda de Anahí y cultura guaraní del Litoral argentino.",
        {"regiones": ["Noreste", "Litoral"], "provincias": ["Corrientes", "Misiones"], "periodo_historico": ["colonial"], "temas": ["pueblos_originarios", "folclore"]},
        {"fuentes_investigacion": ["https://itch.io"]},
        personajes=[{"nombre": "Anahí", "tipo": "folclore", "rol": "protagonista", "descripcion": "Princesa guaraní de la leyenda del ceibo"}],
        verificado=True,
    ),
    game(
        "tito-en-el-humedal",
        "Tito en el Humedal",
        None,
        "publicado",
        v("principal", None, None),
        "Desarrollador educativo argentino",
        "Argentina",
        ["Web"],
        ["educativo", "trivia"],
        "Trivia educativa sobre el humedal de Melincué en Santa Fe.",
        {"regiones": ["Litoral"], "provincias": ["Santa Fe"], "periodo_historico": ["contemporaneo"], "temas": ["geografia", "medio_ambiente", "educacion"]},
        {"fuentes_investigacion": ["https://itch.io"]},
        verificado=True,
    ),
    game(
        "argentina-y-sus-provincias",
        "Argentina Y Sus Provincias",
        None,
        "publicado",
        v("principal", None, None),
        "Desarrollador educativo",
        "Argentina",
        ["Web", "PC"],
        ["educativo", "puzzle"],
        "Juego para memorizar la geografía política de Argentina y sus provincias.",
        {"regiones": ["Nacional"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["geografia", "educacion"]},
        {"fuentes_investigacion": ["https://itch.io"]},
        verificado=True,
    ),
]
