"""Entradas adicionales para la base de datos."""
from generate_db import game, v


EXTRA_GAMES = [
    game(
        "pc-futbol-60-argentina",
        "PC Fútbol 6.0 Argentina",
        1998,
        "publicado",
        v(None, None, "principal", "liga_futbol"),
        "Dinamic Multimedia",
        "España",
        ["PC"],
        ["deportes", "simulacion", "estrategia"],
        "Versión argentina de PC Fútbol 6.0 con Primera División, Copa Argentina y divisiones inferiores.",
        {"regiones": [], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["deporte"]},
        {"fuentes_investigacion": ["https://www.dekazeta.net/foro/files/file/4226-pc-f%C3%BAtbol-60-argentina/"]},
        deporte={"deporte": "futbol", "competicion": ["Primera División Argentina"], "equipos_destacados": [], "modo": "gestion_liga"},
    ),
    game(
        "pc-futbol-70-argentina",
        "PC Fútbol 7.0 Argentina",
        1998,
        "publicado",
        v(None, None, "principal", "liga_futbol"),
        "Dinamic Multimedia",
        "España",
        ["PC"],
        ["deportes", "simulacion", "estrategia"],
        "Última gran entrega de la saga PC Fútbol centrada en el fútbol argentino.",
        {"regiones": [], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["deporte"]},
        {"fuentes_investigacion": ["https://www.pcfutbol.com/"]},
        deporte={"deporte": "futbol", "competicion": ["Primera División Argentina"], "equipos_destacados": [], "modo": "gestion_liga"},
        serie="pc-futbol-argentina",
        edicion="7.0",
    ),
    game(
        "pes-2017-afa",
        "Pro Evolution Soccer 2017 (Licencia AFA ampliada)",
        2016,
        "publicado",
        v(None, None, "principal", "liga_futbol"),
        "Konami",
        "Japón",
        ["PlayStation", "Xbox", "PC"],
        ["deportes", "simulacion"],
        "PES 2017 con 30 equipos argentinos licenciados y estadios Bombonera y Monumental.",
        {"regiones": [], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["deporte"]},
        {"fuentes_investigacion": ["https://www.konami.com/games/eu/en/topics/13834/"]},
        deporte={"deporte": "futbol", "competicion": ["Primera División Argentina"], "equipos_destacados": ["Boca Juniors", "River Plate"], "modo": "simulacion_partido"},
    ),
    game(
        "truco-arbiser-1982",
        "Truco Arbiser",
        1982,
        "publicado",
        v("principal", "principal", None),
        "Enrique y Ariel Arbiser",
        "Argentina",
        ["PC", "Otro"],
        ["cartas", "simulacion"],
        "Primer videojuego comercial latinoamericano: simulación del truco argentino con frases y música de tango.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["juegos_tradicionales", "cultura_popular"]},
        {"fuentes_investigacion": ["https://www-2.dc.uba.ar/charlas/lud/truco/"]},
        personajes=[{"nombre": "Jugador de truco", "tipo": "arquetipo", "rol": "protagonista", "descripcion": "Representa la cultura del truco"}],
        verificado=True,
    ),
    game(
        "reversion-the-escape",
        "Reversion: The Escape",
        2014,
        "publicado",
        v("principal", None, None),
        "3f Interactive",
        "Argentina",
        ["PC", "Android", "iOS"],
        ["aventura", "point_and_click"],
        "Aventura point-and-click en Buenos Aires devastada en 2035; el protagonista despierta en el Garrahan.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["ciencia_ficcion"]},
        {"itch": "https://3finteractive.itch.io/reversion-1-the-escape", "fuentes_investigacion": ["https://www.videojuegosargentinos.com.ar/developer/3f-interactive"]},
    ),
    game(
        "reversion-the-meeting",
        "Reversion: The Meeting",
        2014,
        "publicado",
        v("principal", None, None),
        "3f Interactive",
        "Argentina",
        ["PC"],
        ["aventura", "point_and_click"],
        "Segundo capítulo de la trilogía Reversion en las ruinas de Buenos Aires.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["ciencia_ficcion"]},
        {"itch": "https://3finteractive.itch.io/reversion-2-the-meeting", "fuentes_investigacion": ["https://www.videojuegosargentinos.com.ar/developer/3f-interactive"]},
    ),
    game(
        "reversion-the-return",
        "Reversion: The Return",
        2020,
        "publicado",
        v("principal", None, None),
        "3f Interactive",
        "Argentina",
        ["PC"],
        ["aventura", "point_and_click"],
        "Capítulo final de Reversion ambientado en Buenos Aires post-apocalíptica.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["ciencia_ficcion"]},
        {"itch": "https://3finteractive.itch.io/reversion-3-the-return", "fuentes_investigacion": ["https://www.videojuegosargentinos.com.ar/developer/3f-interactive"]},
    ),
    game(
        "conur-life",
        "Conur Life",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Lutte",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "GTA-like en pixel art ambientado en San Hugo, ciudad ficticia inspirada en Florencio Varela.",
        {"regiones": ["Pampeana"], "provincias": ["Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["conurbano", "cultura_urbana"]},
        {"fuentes_investigacion": ["https://www.extragamers.com.ar/2022/04/juegos-argentinos-ambientados-en-buenos-aires.html"]},
        verificado=True,
    ),
    game(
        "the-lost-land-bahia-blanca",
        "The Lost Land of Bahía Blanca",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Libromancy Studios",
        "Argentina",
        ["PC"],
        ["aventura", "rpg", "visual_novel"],
        "Aventura gráfica fantástica sobre Bahía Blanca bajo una dictadura vampírica.",
        {"regiones": ["Pampeana"], "provincias": ["Buenos Aires"], "periodo_historico": ["siglo_xx"], "temas": ["historia", "ficcion"]},
        {"itch": "https://libromancy-studios.itch.io/the-lost-land-of-bahia-blanca-prologue", "fuentes_investigacion": ["https://reconectados.com.ar/eva-play-online-el-catalogo-digital-ya-se-encuentra-disponible-con-mas-de-100-juegos-nacionales/"]},
    ),
    game(
        "bienvenidos-a-la-matanza",
        "Bienvenidos a La Matanza",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Esteban M.",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "Open world de acción inspirado en el conurbano bonaerense estilo GTA villero.",
        {"regiones": ["Pampeana"], "provincias": ["Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["conurbano"]},
        {"fuentes_investigacion": ["https://elplanteo.com/bienvenidos-a-la-matanza/"]},
        verificado=True,
    ),
    game(
        "portenolandia",
        "Porteñolandia",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Agustín y Federico",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "Open world con Palermo, San Telmo, Obelisco, subte y truco porteño.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["porteñidad", "cultura_urbana"]},
        {"fuentes_investigacion": ["https://urgente24.com/omni/se-viene-portenolandia-el-gta-argentino-piqueteros-y-noches-truco-n581400"]},
        verificado=True,
    ),
    game(
        "la-salamanca",
        "La Salamanca",
        None,
        "en_desarrollo",
        v("principal", "principal", None),
        "Carpincho Estudio",
        "Argentina",
        ["PC"],
        ["terror", "puzzle"],
        "Terror y puzzles basado en la leyenda de La Salamanca de los Llanos (Santiago del Estero).",
        {"regiones": ["Noroeste"], "provincias": ["Santiago del Estero"], "periodo_historico": ["ficcion_sin_epoca"], "temas": ["folclore", "terror"]},
        {"fuentes_investigacion": ["https://www.airedesantafe.com.ar/gaming/la-salamanca-el-videojuego-terror-desarrollado-rosario-que-causa-furor-las-redes-n595131"]},
        personajes=[{"nombre": "La Salamanca", "tipo": "folclore", "rol": "secundario", "descripcion": "Leyenda santiagueña del pacto con el diablo"}],
        verificado=True,
    ),
    game(
        "luz-mala",
        "Luz Mala",
        None,
        "prototipo",
        v("principal", "principal", None),
        "Sandro Wainmaier",
        "Argentina",
        ["PC"],
        ["aventura", "plataformas"],
        "Demo donde el jugador encarna a la Luz Mala, leyenda rioplatense que aparece en los campos.",
        {"regiones": ["Pampeana", "Litoral"], "provincias": [], "periodo_historico": ["ficcion_sin_epoca"], "temas": ["folclore"]},
        {"fuentes_investigacion": ["https://www.extragamers.com.ar/2026/05/luz-mala-la-leyenda-argentina-que-se-convierte-en-videojuego-ya-tiene-su-demo.html"]},
        personajes=[{"nombre": "Luz Mala", "tipo": "folclore", "rol": "protagonista", "descripcion": "Espectro luminoso del folclore pampeano"}],
        verificado=True,
    ),
    game(
        "flora-ceibo-seeds",
        "Flora and the Ceibo Seeds",
        None,
        "early_access",
        v("principal", "principal", None),
        "Alejandro Andes, Amilcar Kippes",
        "Argentina",
        ["PC"],
        ["aventura", "educativo"],
        "Aventura 3D sobre leyendas originarias argentinas y problemática ambiental del ceibo.",
        {"regiones": ["Nacional"], "provincias": [], "periodo_historico": ["precolombino", "contemporaneo"], "temas": ["folclore", "medio_ambiente", "pueblos_originarios"]},
        {"steam": "https://store.steampowered.com/app/2600260/Flora_and_the_Ceibo_Seeds/", "fuentes_investigacion": ["https://store.steampowered.com/app/2600260/Flora_and_the_Ceibo_Seeds/"]},
        verificado=True,
    ),
    game(
        "proceres-san-martin",
        "PRÓCERES: San Martín",
        None,
        "publicado",
        v(None, "principal", None),
        "SETENTIA Studios",
        "Argentina",
        ["Web"],
        ["educativo", "estrategia"],
        "Juego educativo web sobre el Cruce de los Andes y la batalla de Maipú con José de San Martín.",
        {"regiones": ["Cuyo", "Cuyo transandino"], "provincias": ["Mendoza"], "periodo_historico": ["independencia"], "temas": ["historia", "educacion"]},
        {"itch": "https://setentia-studios.itch.io/proceres-san-martin", "fuentes_investigacion": ["https://setentia-studios.itch.io/proceres-san-martin"]},
        personajes=[{"nombre": "José de San Martín", "tipo": "historico", "rol": "protagonista", "descripcion": "Libertador de Argentina, Chile y Perú"}],
        metadatos={"idiomas": ["es"], "multijugador": False, "precio": "gratuito", "rating": {}, "tipo": "juego"},
    ),
    game(
        "gran-malvina",
        "Gran Malvina",
        None,
        "prototipo",
        v("principal", None, None),
        "Ezequiel Pirrotta, IVZ",
        "Argentina",
        ["Web"],
        ["accion", "shooter"],
        "Top-down shooter prototipo sobre un soldado argentino en la Guerra de Malvinas de 1982.",
        {"regiones": ["Atlántico Sur"], "provincias": [], "periodo_historico": ["siglo_xx"], "temas": ["guerra_de_malvinas"]},
        {"itch": "https://ezequielpirrotta.itch.io/gran-malvina", "fuentes_investigacion": ["https://ezequielpirrotta.itch.io/gran-malvina"]},
    ),
    game(
        "gaucho-liberacion",
        "Gaucho Liberación",
        None,
        "en_desarrollo",
        v("principal", "principal", None),
        "Bacord Games",
        "Argentina",
        ["PC"],
        ["accion", "aventura"],
        "Juego de vida gauchesca con costumbres y tradiciones de la Argentina rural histórica.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["siglo_xix"], "temas": ["gauchesco", "historia"]},
        {"fuentes_investigacion": ["https://www.gitgud.com.ar/cuando-un-videojuego-es-argentino-definicion/"]},
        personajes=[{"nombre": "Gaucho", "tipo": "arquetipo", "rol": "protagonista", "descripcion": "Protagonista gauchesco"}],
        verificado=True,
    ),
    game(
        "aconcagua-1999",
        "Aconcagua",
        1999,
        "publicado",
        v("principal", None, None),
        "SCEI / Japan Studio",
        "Japón",
        ["PlayStation"],
        ["aventura", "supervivencia"],
        "Aventura de supervivencia en una Mendoza ficticia tras un accidente de avión en el Aconcagua.",
        {"regiones": ["Cuyo"], "provincias": ["Mendoza"], "periodo_historico": ["contemporaneo"], "temas": ["geografia", "supervivencia"]},
        {"fuentes_investigacion": ["https://www.infobae.com/gaming/2021/01/17/9-videojuegos-con-niveles-ambientados-en-argentina-y-la-eleccion-de-mendoza-para-hitman-3/"]},
    ),
    game(
        "bloodrayne-argentina",
        "BloodRayne (Argentina)",
        2002,
        "publicado",
        v("referencia_menor", None, None),
        "Terminal Reality",
        "Estados Unidos",
        ["PC", "PlayStation", "Xbox"],
        ["accion", "terror"],
        "Niveles en una base nazi oculta en la Patagonia argentina posterior a la Segunda Guerra Mundial.",
        {"regiones": ["Patagonia"], "provincias": [], "periodo_historico": ["siglo_xx"], "temas": ["historia", "ficcion"]},
        {"fuentes_investigacion": ["https://www.infobae.com/gaming/2021/01/17/9-videojuegos-con-niveles-ambientados-en-argentina-y-la-eleccion-de-mendoza-para-hitman-3/"]},
    ),
    game(
        "syndicate-buenos-aires",
        "Syndicate (Buenos Aires 2069)",
        2012,
        "publicado",
        v("referencia_menor", None, None),
        "Starbreeze",
        "Suecia",
        ["PC", "PlayStation", "Xbox"],
        ["shooter", "accion"],
        "Nivel de Buenos Aires futurista en 2069 dentro del reboot de Syndicate.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["ciencia_ficcion"]},
        {"fuentes_investigacion": ["https://www.infobae.com/gaming/2021/01/17/9-videojuegos-con-niveles-ambientados-en-argentina-y-la-eleccion-de-mendoza-para-hitman-3/"]},
    ),
    game(
        "chameleon-buenos-aires",
        "Chameleon (Puerto de Buenos Aires)",
        2006,
        "publicado",
        v("referencia_menor", None, None),
        "Cauldron",
        "República Checa",
        ["PC", "PlayStation", "Xbox"],
        ["accion", "sigilo"],
        "Nivel de espionaje ambientado en el puerto de Buenos Aires.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["geografia"]},
        {"fuentes_investigacion": ["https://www.infobae.com/gaming/2021/01/17/9-videojuegos-con-niveles-ambientados-en-argentina-y-la-eleccion-de-mendoza-para-hitman-3/"]},
    ),
    game(
        "battlefield-bad-company-2-andes",
        "Battlefield: Bad Company 2 (Andes)",
        2010,
        "publicado",
        v("referencia_menor", None, None),
        "DICE",
        "Suecia",
        ["PC", "PlayStation", "Xbox"],
        ["shooter", "accion"],
        "Misiones 'Metal Pesado' y 'Objetivo de Gran Valor' ambientadas en los Andes patagónicos argentinos.",
        {"regiones": ["Patagonia"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["geografia"]},
        {"fuentes_investigacion": ["https://www.infobae.com/gaming/2021/01/17/9-videojuegos-con-niveles-ambientados-en-argentina-y-la-eleccion-de-mendoza-para-hitman-3/"]},
    ),
    game(
        "cod-ghosts-clockwork",
        "Call of Duty: Ghosts — Clockwork",
        2013,
        "publicado",
        v("referencia_menor", None, None),
        "Infinity Ward",
        "Estados Unidos",
        ["PC", "PlayStation", "Xbox"],
        ["shooter", "accion"],
        "Misión de sigilo en los Andes patagónicos de Argentina.",
        {"regiones": ["Patagonia"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["geografia"]},
        {"fuentes_investigacion": ["https://callofduty.fandom.com/wiki/Clockwork"]},
    ),
    game(
        "fifa-street-caminito",
        "FIFA Street (Caminito)",
        2005,
        "publicado",
        v("referencia_menor", None, None),
        "EA Sports",
        "Estados Unidos",
        ["PlayStation", "Xbox"],
        ["deportes", "carreras"],
        "Modo historia con nivel ambientado en Caminito, La Boca, Buenos Aires.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["deporte", "cultura_urbana"]},
        {"fuentes_investigacion": ["https://www.infobae.com/gaming/2021/01/17/9-videojuegos-con-niveles-ambientados-en-argentina-y-la-eleccion-de-mendoza-para-hitman-3/"]},
    ),
    game(
        "fast-furious-showdown-aeroparque",
        "Fast & Furious: Showdown (Aeroparque)",
        2013,
        "publicado",
        v("referencia_menor", None, None),
        "Saber Interactive",
        "Estados Unidos",
        ["PC", "PlayStation", "Xbox"],
        ["carreras", "accion"],
        "Circuito inspirado en Aeroparque y el Río de la Plata en Buenos Aires.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["geografia"]},
        {"fuentes_investigacion": ["https://www.infobae.com/gaming/2021/01/17/9-videojuegos-con-niveles-ambientados-en-argentina-y-la-eleccion-de-mendoza-para-hitman-3/"]},
    ),
    game(
        "civ6-buenos-aires",
        "Civilization VI — Buenos Aires (city-state)",
        2016,
        "publicado",
        v("referencia_menor", None, None),
        "Firaxis Games",
        "Estados Unidos",
        ["PC", "PlayStation", "Xbox", "Nintendo"],
        ["estrategia", "simulacion"],
        "Buenos Aires como city-state industrial jugable en Civilization VI.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["geografia"]},
        {"fuentes_investigacion": ["https://civilization.fandom.com/wiki/Buenos_Aires_(Civ6)"]},
        metadatos={"idiomas": ["es", "en"], "multijugador": True, "precio": None, "rating": {}, "tipo": "juego"},
    ),
    game(
        "civ6-mod-argentina",
        "Civilization VI — Mod Argentina (Leugi)",
        None,
        "publicado",
        v("referencia_menor", "referencia_menor", None),
        "Leugi (modder)",
        "Comunidad",
        ["PC"],
        ["estrategia", "simulacion"],
        "Mod de Workshop que agrega Argentina como civilización con San Martín, Eva Perón y gauchos.",
        {"regiones": ["Nacional"], "provincias": [], "periodo_historico": ["siglo_xix", "siglo_xx"], "temas": ["historia"]},
        {"steam_workshop": "https://steamcommunity.com/sharedfiles/filedetails/?id=910530559", "fuentes_investigacion": ["https://steamcommunity.com/sharedfiles/filedetails/?id=910530559"]},
        personajes=[
            {"nombre": "José de San Martín", "tipo": "historico", "rol": "seleccionable", "descripcion": "Líder alternativo del mod"},
            {"nombre": "Eva Perón", "tipo": "historico", "rol": "seleccionable", "descripcion": "Líder alternativo del mod"},
        ],
        metadatos={"idiomas": ["es", "en"], "multijugador": True, "precio": "gratuito", "rating": {}, "tipo": "mod"},
    ),
    game(
        "golazo-soccer-league",
        "Golazo! Soccer League",
        2020,
        "publicado",
        v(None, None, "referencia_menor", "liga_futbol"),
        "Purple Tree S.R.L.",
        "Argentina",
        ["PC", "Nintendo"],
        ["deportes", "arcade"],
        "Fútbol arcade desarrollado en Argentina con modo copa internacional que incluye la selección argentina.",
        {"regiones": [], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["deporte"]},
        {"steam": "https://store.steampowered.com/app/1431040/Golazo_Soccer_League/", "fuentes_investigacion": ["https://pressover.news/noticias/golazo-juego-de-futbol-hecho-en-argentina-sale-manana-en-switch/"]},
        deporte={"deporte": "futbol", "competicion": ["Copa internacional"], "equipos_destacados": ["Selección Argentina"], "modo": "simulacion_partido"},
        grado_relevancia_argentina="menor",
        ejes_culturales=["deporte"],
    ),
    game(
        "yo-matias-futbol-5",
        "Yo Matías: Fútbol 5",
        2003,
        "publicado",
        v(None, "principal", "referencia_menor", "liga_futbol"),
        "Caimán Co. / PC3",
        "Argentina",
        ["PC"],
        ["deportes"],
        "Juego de fútbol 5 con el personaje Matías de la tira cómica argentina.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["deporte", "cultura_popular"]},
        {"fuentes_investigacion": ["https://www.abandonsocios.org/index.php?topic=15458.0"]},
        personajes=[{"nombre": "Matías", "tipo": "literario", "rol": "protagonista", "descripcion": "Personaje de Sendra"}],
        deporte={"deporte": "futbol", "competicion": ["Fútbol 5 amateur"], "equipos_destacados": [], "modo": "simulacion_partido"},
    ),
    game(
        "yo-matias-fantasmas-calabazas",
        "Yo Matías: Fantasmas y Calabazas",
        2001,
        "publicado",
        v(None, "principal", None),
        "Caimán Co. / PC3",
        "Argentina",
        ["PC"],
        ["plataformas", "aventura"],
        "Segunda entrega de la saga Yo Matías con aventuras oníricas del personaje cómico argentino.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["cultura_popular"]},
        {"fuentes_investigacion": ["https://archive.org/details/yomatias2"]},
        personajes=[{"nombre": "Matías", "tipo": "literario", "rol": "protagonista", "descripcion": "Personaje de Sendra"}],
    ),
    game(
        "noir-storm",
        "Noir Storm",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Diskeletton Studios",
        "Argentina",
        ["PC"],
        ["aventura", "point_and_click"],
        "Aventura noir ambientada en Buenos Aires de 1952 con detective privado.",
        {"regiones": ["Pampeana"], "provincias": ["Ciudad Autónoma de Buenos Aires"], "periodo_historico": ["siglo_xx"], "temas": ["cultura_urbana", "cine_negro"]},
        {"fuentes_investigacion": ["https://www.extragamers.com.ar/2022/04/juegos-argentinos-ambientados-en-buenos-aires.html"]},
        verificado=True,
    ),
    game(
        "delta-kayak-parque-del-delta",
        "Parque del Delta (Delta Kayak)",
        None,
        "en_desarrollo",
        v("principal", None, None),
        "Eibriel",
        "Argentina",
        ["PC"],
        ["terror", "aventura"],
        "Terror de exploración en el Delta del Paraná con transporte y geografía real.",
        {"regiones": ["Litoral"], "provincias": ["Buenos Aires", "Entre Ríos"], "periodo_historico": ["contemporaneo"], "temas": ["geografia", "medio_ambiente"]},
        {"steam": "https://store.steampowered.com/app/2632680/Delta_Kayak/", "fuentes_investigacion": ["https://club.steam250.com/app/2632680"]},
        verificado=True,
    ),
    game(
        "desvelado-2024",
        "Desvelado",
        2024,
        "publicado",
        v("principal", None, None),
        "Estudio argentino",
        "Argentina",
        ["PC"],
        ["plataformas", "aventura"],
        "Plataformero 2D con estética argentina sobre un vampiro infantil que debe volver antes del amanecer.",
        {"regiones": ["Pampeana"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["cultura_popular"]},
        {"fuentes_investigacion": ["https://pressover.news/articulos/los-mejores-videojuegos-argentinos-de-2024/"]},
        verificado=True,
    ),
    game(
        "deep-beyond-2024",
        "Deep Beyond",
        2024,
        "publicado",
        v("principal", None, None),
        "Estudio platense",
        "Argentina",
        ["PC"],
        ["aventura", "puzzle"],
        "Thriller narrativo de puzzles con identidad platense.",
        {"regiones": ["Pampeana"], "provincias": ["Buenos Aires"], "periodo_historico": ["contemporaneo"], "temas": ["cultura_urbana"]},
        {"fuentes_investigacion": ["https://pressover.news/articulos/los-mejores-videojuegos-argentinos-de-2024/"]},
        verificado=True,
    ),
    game(
        "stellar-mess-princess-conundrum",
        "Stellar Mess: The Princess Conundrum",
        2023,
        "publicado",
        v("principal", None, None),
        "Sekiz Bitz",
        "Argentina",
        ["PC"],
        ["aventura", "point_and_click"],
        "Aventura point-and-click con protagonista de tienda de cómics del sur argentino.",
        {"regiones": ["Patagonia"], "provincias": [], "periodo_historico": ["contemporaneo"], "temas": ["cultura_popular"]},
        {"mobygames": "https://www.mobygames.com/game/200114/stellar-mess-the-princess-conundrum/", "fuentes_investigacion": ["https://www.mobygames.com/game/200114/stellar-mess-the-princess-conundrum/"]},
    ),
    game(
        "ara-history-untold-evita",
        "Ara: History Untold — Eva Perón",
        2024,
        "publicado",
        v(None, "referencia_menor", None),
        "Oxide Games",
        "Estados Unidos",
        ["PC", "Xbox"],
        ["estrategia", "simulacion"],
        "Estrategia 4X con Eva Perón como líder jugable de Argentina.",
        {"regiones": ["Nacional"], "provincias": [], "periodo_historico": ["siglo_xx"], "temas": ["historia", "politica"]},
        {"fuentes_investigacion": ["https://www.oxidegames.com/"]},
        personajes=[{"nombre": "Eva Perón", "tipo": "historico", "rol": "seleccionable", "descripcion": "Líder de Argentina en el juego"}],
        verificado=True,
    ),
]
