"""Lote 6: barrido Steam — referencia menor internacional."""
from generate_db import game, v

STEAM_BATCH6_GAMES = [
    game(
        "dcs-south-atlantic",
        "DCS: South Atlantic",
        None,
        "publicado",
        v("referencia_menor", None, None),
        "Eagle Dynamics / Specter Studios",
        "Rusia",
        ["PC"],
        ["simulacion"],
        "Mapa de simulación aérea y marítima del Atlántico Sur con Argentina, Chile y las Islas Malvinas tal como son hoy.",
        {
            "regiones": ["Patagonia", "Nacional"],
            "provincias": ["Tierra del Fuego", "Santa Cruz"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["guerra_de_malvinas", "geografia"],
        },
        {
            "steam": "https://store.steampowered.com/app/2017210/DCS_South_Atlantic/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2017210/DCS_South_Atlantic/"],
        },
        ejes_culturales=["memoria", "geografia"],
        tipo_obra="comercial",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "command-falklands",
        "Command:MO - Falklands",
        None,
        "publicado",
        v("referencia_menor", "referencia_menor", None),
        "Command Development Team",
        "Estados Unidos",
        ["PC"],
        ["estrategia", "simulacion"],
        "Wargame moderno con escenarios jugables de la Guerra de Malvinas entre Argentina y el Reino Unido.",
        {
            "regiones": ["Patagonia"],
            "provincias": ["Tierra del Fuego"],
            "periodo_historico": ["siglo_xx"],
            "temas": ["guerra_de_malvinas", "historia"],
        },
        {
            "steam": "https://store.steampowered.com/app/2141010/CommandMO__Falklands/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/2141010/CommandMO__Falklands/"],
        },
        ejes_culturales=["memoria", "historia"],
        tipo_obra="comercial",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "dakar-18-argentina",
        "Dakar 18",
        2018,
        "publicado",
        v("referencia_menor", None, None),
        "Bigben Interactive",
        "Francia",
        ["PC", "PlayStation", "Xbox"],
        ["deportes", "simulacion"],
        "Simulador oficial del Dakar con etapas en Argentina; incluye el DLC Desafío Ruta 40 Rally con tramos del noroeste argentino.",
        {
            "regiones": ["Noroeste", "Nacional"],
            "provincias": ["Salta", "Jujuy", "Córdoba"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["deporte", "geografia"],
        },
        {
            "steam": "https://store.steampowered.com/app/767390/Dakar_18/",
            "fuentes_investigacion": [
                "https://store.steampowered.com/app/767390/Dakar_18/",
                "https://store.steampowered.com/app/989740/Dakar_18__Desafo_Ruta_40_Rally/",
            ],
        },
        ejes_culturales=["deporte", "geografia"],
        tipo_obra="comercial",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "dirt-rally-2-argentina",
        "DiRT Rally 2.0",
        2019,
        "publicado",
        v("referencia_menor", None, None),
        "Codemasters",
        "Reino Unido",
        ["PC", "PlayStation", "Xbox"],
        ["deportes", "simulacion"],
        "Rally oficial con pruebas en caminos de tierra argentinos, entre ellas el tramo de Catapulta en el NOA.",
        {
            "regiones": ["Noroeste", "Nacional"],
            "provincias": ["Catamarca", "Salta"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["deporte", "geografia"],
        },
        {
            "steam": "https://store.steampowered.com/app/690790/DiRT_Rally_20/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/690790/DiRT_Rally_20/"],
        },
        ejes_culturales=["deporte", "geografia"],
        tipo_obra="comercial",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "wars-curupayti-1866",
        "Wars Across The World: Curupayti 1866",
        None,
        "publicado",
        v("referencia_menor", "referencia_menor", None),
        "Strategiae",
        "Francia",
        ["PC"],
        ["estrategia", "simulacion"],
        "Escenario DLC sobre la batalla de Curupaytí (1866) en la Guerra del Paraguay, con participación de fuerzas argentinas.",
        {
            "regiones": ["Litoral"],
            "provincias": ["Corrientes"],
            "periodo_historico": ["siglo_xix"],
            "temas": ["historia"],
        },
        {
            "steam": "https://store.steampowered.com/app/1996050/Wars_Across_The_World__Curupayti_1866/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1996050/Wars_Across_The_World__Curupayti_1866/"],
        },
        ejes_culturales=["historia"],
        tipo_obra="comercial",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "wrc-10-argentina",
        "WRC 10 FIA World Rally Championship",
        2021,
        "publicado",
        v("referencia_menor", None, None),
        "KT Racing",
        "Italia",
        ["PC", "PlayStation", "Xbox"],
        ["deportes", "simulacion"],
        "Rally oficial del campeonato mundial con la prueba de El Cóndor en Córdoba, Argentina, entre las etapas licenciadas.",
        {
            "regiones": ["Nacional"],
            "provincias": ["Córdoba"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["deporte", "geografia"],
        },
        {
            "steam": "https://store.steampowered.com/app/1462810/WRC_10_FIA_World_Rally_Championship/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/1462810/WRC_10_FIA_World_Rally_Championship/"],
        },
        ejes_culturales=["deporte", "geografia"],
        tipo_obra="comercial",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
    game(
        "aws-argentina-wingshooting",
        "AWS Argentina Wingshooting Simulator",
        2017,
        "publicado",
        v("referencia_menor", None, None),
        "Curse Box Studios",
        "Estados Unidos",
        ["PC"],
        ["simulacion", "deportes"],
        "Simulador de caza de aves en humedales y escenarios del noreste argentino, con especies autóctonas.",
        {
            "regiones": ["Litoral", "Noroeste"],
            "provincias": ["Entre Ríos", "Corrientes"],
            "periodo_historico": ["contemporaneo"],
            "temas": ["geografia", "deporte"],
        },
        {
            "steam": "https://store.steampowered.com/app/718410/AWS_Argentina_Wingshooting_Simulator/",
            "fuentes_investigacion": ["https://store.steampowered.com/app/718410/AWS_Argentina_Wingshooting_Simulator/"],
        },
        ejes_culturales=["geografia"],
        tipo_obra="comercial",
        grado_relevancia_argentina="menor",
        calidad_fuente="tienda",
    ),
]
